# Generated by Django 5.0.4 on 2024-05-04 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('invoice_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('visiting_address', models.TextField()),
                ('general_phone', models.CharField(max_length=20)),
                ('general_email', models.EmailField(max_length=254)),
                ('headoffice', models.CharField(blank=True, max_length=255, null=True)),
                ('our_reference', models.CharField(max_length=255)),
                ('customer', models.BooleanField(default=False)),
                ('customer_number', models.IntegerField(blank=True, null=True)),
                ('supplier', models.BooleanField(default=False)),
                ('supplier_number', models.IntegerField(blank=True, null=True)),
                ('partner', models.BooleanField(default=False)),
                ('private_contact', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Lead', 'Lead'), ('Prospect', 'Prospect'), ('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('industry', models.CharField(choices=[], max_length=100)),
                ('category', models.CharField(choices=[], max_length=100)),
                ('group', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='relations.relation')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='relations.relation')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_invoices', to='relations.relation')),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_active', models.BooleanField(default=False)),
                ('www_address', models.URLField(blank=True)),
                ('invoice_email', models.EmailField(blank=True, max_length=254)),
                ('main_language', models.CharField(blank=True, max_length=50)),
                ('date_of_first_order', models.DateField(blank=True, null=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_info', to='relations.relation')),
            ],
        ),
        migrations.CreateModel(
            name='Freight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_info', to='relations.relation')),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_info', to='relations.relation')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='relations.relation')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('direct_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Dr', 'Dr'), ('Ing', 'Ing')], max_length=10)),
                ('job_function', models.CharField(max_length=255)),
                ('key_contact_person', models.BooleanField(default=False)),
                ('no_longer_works_here', models.BooleanField(default=False)),
                ('do_not_send_mailings', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='relations.relation')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='relations.contact')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='relations.relation')),
            ],
        ),
    ]
